[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = './src/test/Foundry'
cache_path  = 'cache_forge'

[rpc_endpoints]
Arbsepolia = "${ARBSEP_RPC_URL}"

[Arbitrum]
Arbsepolia = { key = "${ARB_API_KEY}" }